---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-5345
    - profile-5345
    - user-5345
    - webserver-5345

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"